export default {
  HOME_TAB_ACTIVED: 'HOME_TAB_ACTIVED',
  MASK_SHOW: 'MASK_SHOW',
  SEARCH_SHOW: 'SEARCH_SHOW',
  SEARCH_TAB_ACTIVE: 'SEARCH_TAB_ACTIVE',
  RESULT_TAB_CHOOSED: 'RESULT_TAB_CHOOSED'
}
